### ISSUE TITLE
Move Signals into a seperate package 

### ISSUE THREAD

**Issue by katungi** [katungi/urban-js#18]
Signals currently are in a file in the utils. But we want to atleast have them seperate from the utils folder to a seperate package.
This should be easy, because I am just exporting the preact signal functions.

**Comment by vareenrose** [comment]
hello, I would like to contribute, can I have this issue? Also I noticed the links on the introduction page of your docs are broken

**Comment by katungi** [comment]
Hey, please go ahead and fix that. I would appreciate that!

**Comment by vareenrose** [comment]
> Hey, please go ahead and fix that. I would appreciate that!

should I do the docs thing it under this issue, or create a new issue. Also I noticed that there's a missing exports key for the urban router package.json, so the import is not working. I can correct that as well, just unsure of your issue creation protocol 😅

**Comment by katungi** [comment]
Hey @ vareenrose, I you can update the docs maybe in a new PR, just for easier reviewing. But awesome work on this issue!

**Comment by vareenrose** [comment]
thanks, it was going to be a different pr, my question was what issue should I attach it to and whether to create a new one

**Comment by katungi** [comment]
Ah yes yes, just assign it to this issue!

**Comment by vareenrose** [comment]
cool thanks
